/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.isen.news

import tornadofx.*
import org.isen.news.view.fx.NewsViewWrapperApp

fun main(args: Array<String>) {
    // launch the tornadofx application
    launch<NewsViewWrapperApp>(args)
}
