import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM.
    id("org.jetbrains.kotlin.jvm").version("1.3.31")
    id("org.openjfx.javafxplugin").version("0.0.8")
    // Apply the application plugin to add support for building a CLI application.
    application
    //kotlin("jvm") version "1.3.71"
}

javafx {
    modules("javafx.controls", "javafx.base","javafx.fxml", "javafx.swing")
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()

    maven(url = "https://jitpack.io") {
        name = "jitpack"
    }
}

dependencies {
    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    // Fuel
    implementation("com.github.kittinunf.fuel:fuel:2.0.1")
    implementation("com.github.kittinunf.fuel:fuel-coroutines:2.0.1")
    implementation("com.github.kittinunf.fuel:fuel-gson:2.0.1")

    // Fuse (not implemented yet because of ExperimentalTime annotation issues)
    compile(group= "com.github.kittinunf.fuse", name= "fuse", version= "1.0.0-beta1")

    // log4j
    implementation("org.apache.logging.log4j:log4j-api-kotlin:1.0.0")
    implementation("org.apache.logging.log4j:log4j-api:2.11.1")
    implementation("org.apache.logging.log4j:log4j-core:2.11.1")

    compile("no.tornado:tornadofx:1.7.19")
    compile(group= "net.java.openjfx.backport", name= "openjfx-78-backport-compat", version= "1.8.0.1")
    compile("org.kordamp.bootstrapfx:bootstrapfx-core:0.2.4")
}

application {
    // Define the main class for the application
    mainClassName = "org.isen.news.AppKt"
}

tasks.compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
tasks.compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
val compileKotlin: KotlinCompile by tasks
compileKotlin.kotlinOptions {
    jvmTarget = "1.8"
}
val compileTestKotlin: KotlinCompile by tasks
compileTestKotlin.kotlinOptions {
    jvmTarget = "1.8"
}